### ISSUE TITLE
我感觉这个数据集特别好，但是我搞不懂这个数据集是怎么运行的

### ISSUE THREAD

**Issue by xijinmu** [xiaofeng94/BeDDE-for-defogging#1]
能有相关运行视频吗？准备发论文了，想用这个评价。

**Comment by xiaofeng94** [comment]
Hi, 

目前没有运行视频。

若需使用BeDDE进行测试请参见README.md中的Testing小节。
大概的流程是：按指定格式生产好去雾图像 -> 修改eval_defog_method.m中的参数(method_name和eval_method) -> 运行eval_defog_method.m。
