### ISSUE TITLE
数据集图片问题

### ISSUE THREAD

**Issue by LPengYang** [xiaofeng94/BeDDE-for-defogging#2]
Hi,您好，我们下载了您的数据集，并且按照您给定的流程进行测试，但是我们发现在数据集的Fog子集中的很多图片的边缘存在不规则的黑边，我们猜测应该是为了对齐导致的，但是这样的话对于很多去雾方法会引入额外的误差，比如基于batch的DCP和CAP，比如基于全局特征的NLD，不知道这些问题使如何解决的呢或者是将这写黑边作为数据集本身特性而引入的干扰项呢？

**Comment by xiaofeng94** [comment]
Hey, 

图像的黑边的确是对齐导致的。测试时，我们提供了mask，会排出黑边以及无法对齐的区域。
更多关于mask的信息，请参见我们的论文https://ieeexplore.ieee.org/document/9099036

Best
